### PR TITLE
tuftool: correct spelling of targets-url

### LINKED ISSUE #268: tuftool: --target-url
Some `tuftool` commands have an argument named `--target-url` instead of `--targets-url` and it makes me sad. `download` is one of these commands.

### PR DESCRIPTION
**Pull request by webern**
*Issue #, if available:*

Closes #268

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by etungsten — APPROVED** [review]

**Review by srgothi92 — APPROVED** [review]
This change looks like a breaking change for someone who uses `tuftool`. 
Few things that comes to my mind are `tuf-repo-automation`, steps for root creation, tuftool Readme. I checked `tuf-repo-automation` and  tuftool Readme both of them looks  safe of this change. However,  **steps for root creation** may need some changes, I am not sure ?

**Comment by webern** [comment]
> This change looks like a breaking change for someone who uses `tuftool`.
> Few things that comes to my mind are `tuf-repo-automation`, steps for root creation, tuftool Readme. I checked `tuf-repo-automation` and tuftool Readme both of them looks safe of this change. However, **steps for root creation** may need some changes, I am not sure ?

Yes, agreed this is a breaking change. I will fix the documentation that you mentioned. We will also call this out in the changelog when releasing. I think @etungsten was actually waiting for the next tuftool release to use tuftool for verifying repo soundness, so I think there's no tuftool usage there yet. For other scripts or runbooks, the inconvenience of fixing the command should be minimal.

**Comment by webern** [comment]
>  tuftool Readme.

Actually we used the short form, `-t`. So that's why my find and replace didn't hit the readme.

**Review by zmrow — APPROVED** [review]

**Comment by webern** [comment]
I double-checked Bottlerocket. `pubsys` uses `tuftool` but the only subcommand it uses is `tuftool root`, so we should be fine. Merging.

**Pull request merged**
