### PR TITLE
Upgrade SNAFU to 0.7

### PR DESCRIPTION
**Pull request by shepmaster**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shepmaster** [comment]
Ran rustfmt and force-pushed.

**Comment by jpculp** [comment]
🎸 Thank you again for taking care of this!

It looks like there is a small clippy warning about a redundant closure, but other than that I think this is great! Would you prefer to fix it or would you rather we take care of it?

**Review by zmrow — APPROVED** [review]
:+1: 

LGTM minus clippy's little tantrum.

Thanks again for doing this!

**Review by webern — APPROVED** [review]
Wow, this is a very interesting update to the Snafu library. Adding the `*Snafu` suffix should help out IDE tooling quite a bit, although JetBrains *almost* had it handled by now. The ergonomics of having a ready type `Whatever` and for making stringly types on the fly are very interesting. I'll have to try these out as a replacement for `anyhow` when my complaint is "I don't want to deal with defining variants."

Thank you for updating us with the new version.

**Comment by shepmaster** [comment]
The Clippy lint appears unrelated to these changes, so I added it as a separate commit before the change to SNAFU and force-pushed the branch.

**Review by jpculp — APPROVED** [review]
🚀

**Review by cbgbt — APPROVED** [review]
Thanks for doing this!

**Review by cbgbt — APPROVED** [review]

**Comment by shepmaster** [comment]
Thanks for using SNAFU!

**Pull request merged**
