### PR TITLE
Combined dependabot requested dependency bump

### PR DESCRIPTION
**Pull request by srgothi92**
*Issue #, if available:*

*Description of changes:*
Manually checked `Cargo.lock` to contain expected version  of `log`, `assert_cmd`, `serde_json` and `ring`.
<details>
  <summary>Update Details</summary>

```
    Updating crates.io index
    Updating assert_cmd v1.0.2 -> v1.0.3
    Removing async-stream v0.3.0
    Removing async-stream-impl v0.3.0
    Updating backtrace v0.3.55 -> v0.3.56
    Updating bstr v0.2.14 -> v0.2.15
    Updating bumpalo v3.4.0 -> v3.6.0
      Adding byteorder v1.4.2
    Removing cfg-if v0.1.10
    Updating encoding_rs v0.8.26 -> v0.8.28
    Updating getrandom v0.2.1 -> v0.2.2
    Updating hermit-abi v0.1.17 -> v0.1.18
    Updating httparse v1.3.4 -> v1.3.5
    Updating hyper v0.14.2 -> v0.14.4
    Updating idna v0.2.0 -> v0.2.1
    Updating js-sys v0.3.46 -> v0.3.47
    Updating libc v0.2.82 -> v0.2.86
    Updating log v0.4.13 -> v0.4.14
    Updating object v0.22.0 -> v0.23.0
    Updating pin-project v1.0.4 -> v1.0.5
    Updating pin-project-internal v1.0.4 -> v1.0.5
    Updating predicates v1.0.6 -> v1.0.7
    Updating predicates-core v1.0.1 -> v1.0.2
    Updating predicates-tree v1.0.1 -> v1.0.2
    Updating rand v0.8.2 -> v0.8.3
      Adding regex-automata v0.1.9
    Updating ring v0.16.19 -> v0.16.20
    Updating serde_json v1.0.61 -> v1.0.62
    Updating sha2 v0.9.2 -> v0.9.3
    Updating standback v0.2.14 -> v0.2.15
    Updating thread_local v1.1.0 -> v1.1.3
    Updating time v0.2.24 -> v0.2.25
    Updating tinyvec v1.1.0 -> v1.1.1
    Updating tokio v1.1.0 -> v1.2.0
    Updating tokio-macros v1.0.0 -> v1.1.0
    Removing tokio-stream v0.1.2
    Updating tokio-util v0.6.2 -> v0.6.3
    Updating tower-service v0.3.0 -> v0.3.1
    Updating tracing v0.1.22 -> v0.1.23
    Updating unicode-normalization v0.1.16 -> v0.1.17
    Updating wasi v0.10.1+wasi-snapshot-preview1 -> v0.10.2+wasi-snapshot-preview1
    Updating wasm-bindgen v0.2.69 -> v0.2.70
    Updating wasm-bindgen-backend v0.2.69 -> v0.2.70
    Updating wasm-bindgen-futures v0.4.19 -> v0.4.20
    Updating wasm-bindgen-macro v0.2.69 -> v0.2.70
    Updating wasm-bindgen-macro-support v0.2.69 -> v0.2.70
    Updating wasm-bindgen-shared v0.2.69 -> v0.2.70
    Updating web-sys v0.3.46 -> v0.3.47
```
</details>

*Testing*
* Ran `make ci`
* Ran `cargo test --features 'integ'` to verify success of `tuftool` integration tests which creates and loads a repository from scratch using `file`, `ssm` and `kms` based keys.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by srgothi92** [comment]
> https://github.com/awslabs/tough/pull/338/files

How can we manually upgrade dependency just in `Cargo.lock` ? `assert_cmd` version is set to `1.0` means it's agnostic to  any patch version upgrade, only file that will change is `Cargo.lock`. I tried deleting `Cargo.lock` and ran `Cargo build --locked -p <package-name>` for each package but it resulted in upgrading dependency version of many other crates along with `assert_cmd`. For now I have excluded `assert_cmd` dependency upgrade out of this PR.

**Comment by webern** [comment]
For this PR all you need to do is run

`cargo update`

then check in the changes to `Cargo.lock`.

In `Cargo.toml`, minor and patch level numbers are kind of meaningless. I would remove all of your `Cargo.toml` changes. My preference would be to say, e.g. `serde = "1"` instead of `serde = "1.0.123"`, but those changes are kind of aesthetic and not necessary.

**Comment by srgothi92** [comment]
Changed as requested by @webern to run `cargo update` and just submit Cargo.lock file.

**Review by webern — APPROVED** [review]

**Review by zmrow — COMMENTED** [review]
:1st_place_medal:

**Pull request merged**
