### PR TITLE
tough v0.7.0 / tough-ssm v0.2.0

### PR DESCRIPTION
**Pull request by zmrow**
*Issue #, if available:*
N/A

*Description of changes:*
* Prepare `tough` to release `0.7.0` to incorporate changes from #158 
* Update `tough-ssm` to depend on `tough 0.7.0`
* Bump `tough-ssm` to `0.2.0`
* Update `tuftool`'s dependencies to reflect new versions of `tough` and `tough-ssm`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by webern — APPROVED** [review]
did you do the cargo dry runs?

**Comment by webern** [comment]
Oops you need to check in the Cargo.lock changes

**Comment by zmrow** [comment]
This push updates the `Cargo.lock`... oops

**Review by tjkirch — APPROVED** [review]

**Review by iliana — APPROVED** [review]

**Comment by iliana** [comment]
Does `tough::schema::Error` have `#[non_exhaustive]`?

**Comment by zmrow** [comment]
@iliana It doesn't, but only because we didn't add any variants to that error type. Should we add `#[non-exhaustive]` there for consistency?

**Comment by iliana** [comment]
> Should we add `#[non-exhaustive]` there for consistency?

IMO yes

**Comment by zmrow** [comment]
@iliana Added `#[non-exhaustive]` to `tough::schema::Error`. :)

**Review by iliana — APPROVED** [review]

**Pull request merged**
