### PR TITLE
feat: add workflow responsible for notifying of new TUF spec releases

### PR DESCRIPTION
**Pull request by rdimitrov**
Signed-off-by: Radoslav Dimitrov <dimitrovr@vmware.com>

*Description of changes:*

The following PR adds a workflow that keeps track and creates an issue for notifying of new TUF specification releases.

The version (v1.0.29) of the spec which is currently used for the verification is added without verifying if this is indeed the version that the `tough` project is compliant with. In that sense, please advise which version to use and I'll update the PR accordingly.

**Note:** Dependent on - https://github.com/theupdateframework/specification/pull/224

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by webern** [comment]
This seems like a good idea to me, any thoughts @zmrow or @iliana ?

**Comment by iliana** [comment]
Seems fine. I also have no idea if tough is v1.0.29-compliant, so maybe we want to figure out the delta of what the spec does to what tough does?

**Comment by webern** [comment]
> no idea if tough is v1.0.29-compliant

True, but it's as good a tag as any for a starting point I suppose. This way at least we'll generate some issues telling us to go figure it out. We can comment on the first one and say we don't know quite which patch version is our starting point.

**Review by webern — APPROVED** [review]

**Comment by rdimitrov** [comment]
Hey, just so you know the dependent PR is now merged in the specification repo 👍

**Review by zmrow — APPROVED** [review]
Seems fine

**Pull request merged**
